local ok, C = pcall(require, "colors")  -- generated by matugen
if not ok then
    -- fallback: Catppuccin Mocha
    C = {
        primary    = "#cba6f7",
        secondary  = "#b4befe",
        surface    = "#1e1e2e",
        on_surface = "#cdd6f4",
    }
end

-- build rgba strings for borders
local function hex_to_rgba(hex, alpha)
    hex = hex:gsub("#", "")
    return string.format("rgba(%sff)", hex):gsub("ff$", alpha or "ff")
end

hl.config({
    general = {
        gaps_in        = 3,
        gaps_out       = 8,
        border_size    = 2,
        col = {
	    active_border   = { colors = { C.primary .. "ff", C.secondary .. "ff" }, angle = 45 },
            inactive_border = { colors = { C.surface .. "cc", C.surface .. "66" },   angle = 45 },
        },
        layout           = "dwindle",
        resize_on_border = true,
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,
        shadow         = { enabled = false },
        blur = {
            enabled           = true,
            size              = 6,
            passes            = 3,
            new_optimizations = true,
            ignore_opacity    = true,
            xray              = false,
        },
    },

    group = {
        col = {
            border_active          = { colors = { C.primary .. "ff",   C.secondary .. "ff" }, angle = 45 },
            border_inactive        = { colors = { C.surface .. "cc",   C.surface .. "66"   }, angle = 45 },
            border_locked_active   = { colors = { C.primary .. "ff",   C.secondary .. "ff" }, angle = 45 },
            border_locked_inactive = { colors = { C.surface .. "cc",   C.surface .. "66"   }, angle = 45 },
        },
    },

    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },

    misc = {
        disable_hyprland_logo = true,
        enable_swallow        = true,
        swallow_regex         = "ghostty|Ghostty",
    },

    ecosystem = {
        no_update_news = true,
    },
})

-- Waybar gets blur applied at the layer level
hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
