# Generated by generate.lua — do not edit
$ml_text     = rgba({{fg_stripped}}ff)
$ml_subtext  = rgba({{fg_dim_stripped}}ff)
$ml_primary  = rgba({{accent_stripped}}ff)
$ml_surface  = rgba({{bg1_stripped}}ff)
$ml_error    = rgba({{red_stripped}}ff)
$ml_success  = rgba({{green_stripped}}ff)
