-- Generated by generate.lua (Carbonfox)
local M = {}
M.primary    = "#{{accent_stripped}}"
M.secondary  = "#{{secondary_stripped}}"
M.surface    = "#{{bg1_stripped}}"
M.on_surface = "#{{fg_stripped}}"
M.error      = "#{{red_stripped}}"
return M
