background    = 0xFF1e2030
base          = 0xFF2f334d
alternate_base = 0xFF1e2030
text          = 0xFFc8d3f5
bright_text   = 0xFFffffff
accent        = 0xFF82aaff
accent_secondary = 0xFFc099ff

font_size       = 13
h1_size         = 19
h2_size         = 15
h3_size         = 13
small_font_size = 11

icon_theme = Papirus-Dark
