-- Generated by matugen
local M = {}
M.primary    = "#{{colors.primary.default.hex_stripped}}"
M.secondary  = "#{{colors.secondary.default.hex_stripped}}"
M.surface    = "#{{colors.surface.default.hex_stripped}}"
M.on_surface = "#{{colors.on_surface.default.hex_stripped}}"
M.error      = "#{{colors.error.default.hex_stripped}}"
return M
